using System;

namespace Sniper.Properties
{
	public static class Tokens
	{
		#pragma warning disable IDE1006 // Naming Styles
		#pragma warning disable CA1707 // Identifiers should not contain underscores
		public const String LOADOUT_SNIPER_AMMO = "LOADOUT_SNIPER_AMMO";
		public const String LOADOUT_SNIPER_PASSIVE = "LOADOUT_SNIPER_PASSIVE";
		public const String SNIPER_AMMO_EXPLOSIVE_DESC = "SNIPER_AMMO_EXPLOSIVE_DESC";
		public const String SNIPER_AMMO_EXPLOSIVE_NAME = "SNIPER_AMMO_EXPLOSIVE_NAME";
		public const String SNIPER_AMMO_STANDARD_DESC = "SNIPER_AMMO_STANDARD_DESC";
		public const String SNIPER_AMMO_STANDARD_NAME = "SNIPER_AMMO_STANDARD_NAME";
		public const String SNIPER_DESC = "SNIPER_DESC";
		public const String SNIPER_NAME = "SNIPER_NAME";
		public const String SNIPER_PASSIVE_CRITICAL_DESC = "SNIPER_PASSIVE_CRITICAL_DESC";
		public const String SNIPER_PASSIVE_CRITICAL_NAME = "SNIPER_PASSIVE_CRITICAL_NAME";
		public const String SNIPER_PASSIVE_HEADSHOT_DESC = "SNIPER_PASSIVE_HEADSHOT_DESC";
		public const String SNIPER_PASSIVE_HEADSHOT_NAME = "SNIPER_PASSIVE_HEADSHOT_NAME";
		public const String SNIPER_PRIMARY_DASH_DESC = "SNIPER_PRIMARY_DASH_DESC";
		public const String SNIPER_PRIMARY_DASH_NAME = "SNIPER_PRIMARY_DASH_NAME";
		public const String SNIPER_PRIMARY_DASH_RELOAD_DESC = "SNIPER_PRIMARY_DASH_RELOAD_DESC";
		public const String SNIPER_PRIMARY_DASH_RELOAD_NAME = "SNIPER_PRIMARY_DASH_RELOAD_NAME";
		public const String SNIPER_PRIMARY_SNIPE_DESC = "SNIPER_PRIMARY_SNIPE_DESC";
		public const String SNIPER_PRIMARY_SNIPE_NAME = "SNIPER_PRIMARY_SNIPE_NAME";
		public const String SNIPER_PRIMARY_SNIPE_RELOAD_DESC = "SNIPER_PRIMARY_SNIPE_RELOAD_DESC";
		public const String SNIPER_PRIMARY_SNIPE_RELOAD_NAME = "SNIPER_PRIMARY_SNIPE_RELOAD_NAME";
		public const String SNIPER_SECONDARY_QUICK_DESC = "SNIPER_SECONDARY_QUICK_DESC";
		public const String SNIPER_SECONDARY_QUICK_NAME = "SNIPER_SECONDARY_QUICK_NAME";
		public const String SNIPER_SECONDARY_STEADY_DESC = "SNIPER_SECONDARY_STEADY_DESC";
		public const String SNIPER_SECONDARY_STEADY_NAME = "SNIPER_SECONDARY_STEADY_NAME";
		public const String SNIPER_SKIN_ALT1_NAME = "SNIPER_SKIN_ALT1_NAME";
		public const String SNIPER_SKIN_ALT2_NAME = "SNIPER_SKIN_ALT2_NAME";
		public const String SNIPER_SKIN_DEFAULT_NAME = "SNIPER_SKIN_DEFAULT_NAME";
		public const String SNIPER_SPECIAL_DECOY_DESC = "SNIPER_SPECIAL_DECOY_DESC";
		public const String SNIPER_SPECIAL_DECOY_NAME = "SNIPER_SPECIAL_DECOY_NAME";
		public const String SNIPER_SPECIAL_KNIFE_DESC = "SNIPER_SPECIAL_KNIFE_DESC";
		public const String SNIPER_SPECIAL_KNIFE_NAME = "SNIPER_SPECIAL_KNIFE_NAME";
		public const String SNIPER_SUBTITLE = "SNIPER_SUBTITLE";
		public const String SNIPER_UTILITY_BACKFLIP_DESC = "SNIPER_UTILITY_BACKFLIP_DESC";
		public const String SNIPER_UTILITY_BACKFLIP_NAME = "SNIPER_UTILITY_BACKFLIP_NAME";
		#pragma warning restore IDE1006 // Naming Styles
		#pragma warning restore CA1707 // Identifiers should not contain underscores
	}
}