// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage( "Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Modules.TextureModule.#cctor" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Special.DecoyReactivation" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Special.KnifeReactivation" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Utility.Backflip" )]
[assembly: SuppressMessage( "Usage", "CA2214:Do not call overridable methods in constructors", Justification = "<Pending>", Scope = "member", Target = "~M:ReinCore.CorePlugin.#ctor" )]
[assembly: SuppressMessage( "Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:ReinCore.CorePlugin.#cctor" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Special.KnifeActivation" )]
[assembly: SuppressMessage( "Performance", "CA1823:Avoid unused private fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.States.Special.DecoyActivation.cloakDuration" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Special.DecoyActivation" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Secondary.QuickScope" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Secondary.DefaultScope" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Primary.Reload.SlideReload" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Primary.Reload.MagReload" )]
[assembly: SuppressMessage( "Performance", "CA1823:Avoid unused private fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.States.Primary.Reload.DefaultReload.origParent" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Primary.Reload.DefaultReload" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Primary.Fire.SlideSnipe" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Primary.Fire.MagSnipe" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Primary.Fire.DefaultSnipe" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Other.DecoyDeathState" )]
[assembly: SuppressMessage( "Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.ScriptableObjects.Custom.SniperTexture.texture" )]
[assembly: SuppressMessage( "Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.ScriptableObjects.Custom.SniperTexture.textureName" )]
[assembly: SuppressMessage( "Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.ScriptableObjects.Custom.SniperTextureSet.sniperTextures" )]
[assembly: SuppressMessage( "Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.InternalLog(BepInEx.Logging.LogLevel,System.Object,System.String,System.Int32)" )]
[assembly: SuppressMessage( "Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.InternalLog(BepInEx.Logging.LogLevel,System.Object,System.String,System.Int32)" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.SniperMain" )]
[assembly: SuppressMessage( "Usage", "CA2243:Attribute string literals should parse correctly", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.SniperMain" )]
[assembly: SuppressMessage( "Performance", "CA1823:Avoid unused private fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Components.ScopeUIController.scopeParent" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetBodyMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetArmorMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetCloakMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetAmmoMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetEmissiveMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetRailMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetThrowKnifeMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.GetKnifeMaterial~UnityEngine.Material" )]
[assembly: SuppressMessage( "Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Modules.DecoyModule.#cctor" )]
[assembly: SuppressMessage( "Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.UIStockController.OnCurrentStockChanged(System.Int32,System.Int32)" )]
[assembly: SuppressMessage( "Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.UIStockController.OnMaxStockChanged(System.Int32,System.Int32)" )]
[assembly: SuppressMessage( "Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.UIStockController.OnMaxStockChanged(System.Int32,System.Int32)" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Data.SniperSkin.CreateAndAddSkin(RoR2.CharacterModel,System.String,System.String,UnityEngine.Sprite)" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.Components.ReloadUIController" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Components.ReloadUIController._barTexture" )]
[assembly: SuppressMessage( "Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.ReloadUIController.OnBarTextureChanged(UnityEngine.Texture2D,UnityEngine.Texture2D)" )]
[assembly: SuppressMessage( "Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.RicochetController.Ricochet(Sniper.Expansions.ExpandableBulletAttack,System.UInt32)~System.Collections.IEnumerator" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Components.ScopeUIController._scoped" )]
[assembly: SuppressMessage( "Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Modules.TextureModule.ScanAndLoadPacks" )]
[assembly: SuppressMessage( "Naming", "CA1724:Type names should not match namespaces", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.Properties.Tools" )]
[assembly: SuppressMessage( "Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.RegisterLanguageTokens" )]
[assembly: SuppressMessage( "Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.RegisterLanguageTokens" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.GetModPrefix(BepInEx.BaseUnityPlugin,System.String)~System.String" )]
[assembly: SuppressMessage( "Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.GetModPrefix(BepInEx.BaseUnityPlugin,System.String)~System.String" )]
[assembly: SuppressMessage( "Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.LoadUnmanagedAssembly(System.String,System.Byte[])~System.String" )]
[assembly: SuppressMessage( "Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.LoadUnmanagedAssembly(System.String,System.Byte[])~System.String" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.DebugF(System.String,System.Object[])" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.InfoF(System.String,System.Object[])" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.MessageF(System.String,System.Object[])" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.WarningF(System.String,System.Object[])" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.ErrorF(System.String,System.Object[])" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.FatalF(System.String,System.Object[])" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.Counter(System.String,System.Int32)" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.ClearCounter(System.Boolean,System.String,System.Int32)" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Log.InternalLogL(BepInEx.Logging.LogLevel,System.Object,System.String,System.Int32)" )]
[assembly: SuppressMessage( "Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Properties.Tools.LoadUnmanagedAssembly(System.String,System.Byte[])~System.String" )]
[assembly: SuppressMessage( "Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.ScriptableObjects.Custom.SniperTextureSet.Merge(Sniper.ScriptableObjects.Custom.SniperTextureSet)" )]
[assembly: SuppressMessage( "Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.ScriptableObjects.Custom.SniperTextureSet.MergeAndReplace(Sniper.ScriptableObjects.Custom.SniperTextureSet)" )]
[assembly: SuppressMessage( "Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.ScriptableObjects.Custom.SniperTextureSet.CheckForDuplicates" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.SkillDefs.DecoySkillDef" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.SkillDefs.KnifeSkillDef" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.SkillDefs.SniperAmmoSkillDef" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.SkillDefs.SniperPassiveSkillDef" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.ScriptableObjects.SniperCameraParams" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.Components.KnifeDeployableSync" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.OnDestroy" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.Start" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.Awake" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.CollisionManager.OnTriggerEnter(UnityEngine.Collider)" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.FixedUpdate" )]
[assembly: SuppressMessage( "Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.CollisionManager.Sniper#Components#IRuntimePrefabComponent#InitializePrefab" )]
[assembly: SuppressMessage( "Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.Sniper#Components#IRuntimePrefabComponent#InitializePrefab" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.CollisionManager.OnEnable" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Sniper.Components.KnifeDeployableSync.CollisionManager.OnDisable" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._scatterTracerTrailMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._baseKnifeTrailMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._explosiveTracerMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._explosiveTracerTrailMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._plasmaTracerMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._plasmaTracerTrailMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._railBase" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._railDefault" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._scatterTracerMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._sniperBase" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._sniperDefaultBase" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._sniperSkin1Base" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._sniperSkin2Base" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._standardTracerMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._standardTracerTrailMaterial" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.MaterialModule._throwKnifeBase" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.States.Special.KnifePickupSlash" )]
[assembly: SuppressMessage( "Performance", "CA1823:Avoid unused private fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.SoundModule.volume_sfx" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.SoundModule.bolt_quickscope" )]
[assembly: SuppressMessage( "Performance", "CA1823:Avoid unused private fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.SoundModule.bolt_quickscope" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.SoundModule.volume_master" )]
[assembly: SuppressMessage( "Performance", "CA1823:Avoid unused private fields", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.SoundModule.volume_master" )]
[assembly: SuppressMessage( "CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.SoundModule.volume_sfx" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railAlt1Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railAlt2Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railAlt3Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railDefaultTextures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperAlt1Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperAlt2Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperAlt3Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperAlt4Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperAlt5Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperTextures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeDefaultTextures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railAlt4Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railAlt5Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railAlt6Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._railTextures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._sniperAlt6Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeAlt1Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeAlt2Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeAlt3Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeAlt4Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeAlt5Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeAlt6Textures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.TextureModule._throwKnifeTextures" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._countMultiplier" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._damageColor" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._damageMultiplier" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._damageTypeAdd" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._damageTypeRemove" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._forceMultiplier" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._hitMaskAdd" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._hitMaskRemove" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._maxSpread" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._minSpread" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._procMultiplier" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._radiusMultiplier" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._spreadPitch" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._spreadYaw" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._stopperMaskAdd" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Data.BulletModifier._stopperMaskRemove" )]
[assembly: SuppressMessage( "Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Sniper.Modules.CatalogModule._plasmaDamageColor" )]
[assembly: SuppressMessage( "Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "<Pending>", Scope = "type", Target = "~T:Sniper.Components.DecoyDeployableSync" )]
