//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rein.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rein.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Wisp.
        /// </summary>
        internal static string lang__ANCIENT_WISP_BODY_NAME {
            get {
                return ResourceManager.GetString("lang__ANCIENT_WISP_BODY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banished and Chained.
        /// </summary>
        internal static string lang__ANCIENT_WISP_BODY_SUBNAME {
            get {
                return ResourceManager.GetString("lang__ANCIENT_WISP_BODY_SUBNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rogue Wisp is a short-ranged, low-mobility, and high-damage survivor. \n These descriptions are incredibly time consuming to write, so good luck!.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_BODY_DESC {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_BODY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue Wisp.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_BODY_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_BODY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style=cIsUtility&gt;Flame Charge&lt;/style&gt; &lt;style=cIsDamage&gt;Empowers&lt;/style&gt; your abilities but decays over time.\nGain &lt;style=cIsDamage&gt;Barrier&lt;/style&gt; based on &lt;style=cIsHealth&gt;Maximum Health&lt;/style&gt; whenever you regain &lt;style=cIsUtility&gt;Flame Charge.&lt;/style&gt;.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_PASSIVE_DESC {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_PASSIVE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lang__WISP_SURVIVOR_PASSIVE_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_PASSIVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire a shockwave for &lt;style=cIsDamage&gt;165% damage.&lt;/style&gt; &lt;style=cIsUtility&gt;Restores Flame Charge&lt;/style&gt; on hit..
        /// </summary>
        internal static string lang__WISP_SURVIVOR_PRIMARY_1_DESC {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_PRIMARY_1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runic Wave.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_PRIMARY_1_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_PRIMARY_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a line of flame pillars that explode for &lt;style=cIsDamage&gt;250% damage.&lt;/style&gt; Enemies hit more than once take reduced damage. Consumes &lt;style=cIsUtility&gt;Flame Charge&lt;/style&gt; on cast..
        /// </summary>
        internal static string lang__WISP_SURVIVOR_SECONDARY_1_DESC {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_SECONDARY_1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Spark.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_SECONDARY_1_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_SECONDARY_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel a beam for &lt;style=cIsDamage&gt;500% damage&lt;/style&gt; per second. &lt;style=cIsUtility&gt;Continues as long as you hold button&lt;/style&gt; &lt;style=cIsUtility&gt;Gain Armor&lt;/style&gt; but &lt;style=cIsHealth&gt;Cannot Move&lt;/style&gt; while firing. Drains &lt;style=cIsUtility&gt;Flame Charge&lt;/style&gt; per second while firing..
        /// </summary>
        internal static string lang__WISP_SURVIVOR_SPECIAL_1_DESC {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_SPECIAL_1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incineration.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_SPECIAL_1_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_SPECIAL_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lang__WISP_SURVIVOR_SUBTITLE_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_SUBTITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an &lt;style=cIsDamage&gt;Inferno&lt;/style&gt; that &lt;style=cIsDamage&gt;Ignites&lt;/style&gt; all enemies for &lt;style=cIsDamage&gt;80% damage&lt;/style&gt; per second. While in an &lt;style=cIsDamage&gt;Inferno&lt;/style&gt;&lt;style=cIsUtility&gt; Move Faster&lt;/style&gt; and &lt;style=cIsUtility&gt;Gain Flame Charge&lt;/style&gt; from &lt;style=cIsDamage&gt;Ignited&lt;/style&gt; enemies..
        /// </summary>
        internal static string lang__WISP_SURVIVOR_UTILITY_1_DESC {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_UTILITY_1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferno.
        /// </summary>
        internal static string lang__WISP_SURVIVOR_UTILITY_1_NAME {
            get {
                return ResourceManager.GetString("lang__WISP_SURVIVOR_UTILITY_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NetLib {
            get {
                object obj = ResourceManager.GetObject("NetLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReinCore {
            get {
                object obj = ResourceManager.GetObject("ReinCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wispscene {
            get {
                object obj = ResourceManager.GetObject("wispscene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wispsurvivor {
            get {
                object obj = ResourceManager.GetObject("wispsurvivor", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
