//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNIPER_UNLOCKABLES_WIP_DESC.
        /// </summary>
        internal static string ach__WIP__desctoken {
            get {
                return ResourceManager.GetString("ach__WIP__desctoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ach__WIP__iconpath {
            get {
                return ResourceManager.GetString("ach__WIP__iconpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIP.
        /// </summary>
        internal static string ach__WIP__identifier {
            get {
                return ResourceManager.GetString("ach__WIP__identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNIPER_UNLOCKABLES_WIP_NAME.
        /// </summary>
        internal static string ach__WIP__nametoken {
            get {
                return ResourceManager.GetString("ach__WIP__nametoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ach__WIP__prereq {
            get {
                return ResourceManager.GetString("ach__WIP__prereq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.WIP.
        /// </summary>
        internal static string ach__WIP__unlockidentifier {
            get {
                return ResourceManager.GetString("ach__WIP__unlockidentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Utility/Backflip.png.
        /// </summary>
        internal static string icon__BackflipIcon {
            get {
                return ResourceManager.GetString("icon__BackflipIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/passive 2/Precise Aim.png.
        /// </summary>
        internal static string icon__CritPassiveIcon {
            get {
                return ResourceManager.GetString("icon__CritPassiveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/UI/CrosshairCenter.png.
        /// </summary>
        internal static string icon__CrosshairCenter {
            get {
                return ResourceManager.GetString("icon__CrosshairCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Special 1/Decoy.png.
        /// </summary>
        internal static string icon__DecoyIcon {
            get {
                return ResourceManager.GetString("icon__DecoyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Special 1/Decoy_Reactivation.png.
        /// </summary>
        internal static string icon__DecoyReactivateIcon {
            get {
                return ResourceManager.GetString("icon__DecoyReactivateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Passive 1/Explosive Ammo.png.
        /// </summary>
        internal static string icon__ExplosiveAmmoIcon {
            get {
                return ResourceManager.GetString("icon__ExplosiveAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/passive 2/Headshot.png.
        /// </summary>
        internal static string icon__HeadshotIcon {
            get {
                return ResourceManager.GetString("icon__HeadshotIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__KnifeIcon {
            get {
                return ResourceManager.GetString("icon__KnifeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__KnifeReactivateIcon {
            get {
                return ResourceManager.GetString("icon__KnifeReactivateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__PlasmaAmmoIcon {
            get {
                return ResourceManager.GetString("icon__PlasmaAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Other/portraitIcon.png.
        /// </summary>
        internal static string icon__PortraitIcon {
            get {
                return ResourceManager.GetString("icon__PortraitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__QuickscopeIcon {
            get {
                return ResourceManager.GetString("icon__QuickscopeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M1/Reload.png.
        /// </summary>
        internal static string icon__ReloadIcon {
            get {
                return ResourceManager.GetString("icon__ReloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__ScatterAmmoIcon {
            get {
                return ResourceManager.GetString("icon__ScatterAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__ShockAmmoIcon {
            get {
                return ResourceManager.GetString("icon__ShockAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string icon__SlideIcon {
            get {
                return ResourceManager.GetString("icon__SlideIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M1/Reload.png.
        /// </summary>
        internal static string icon__SlideReloadIcon {
            get {
                return ResourceManager.GetString("icon__SlideReloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M1/Snipe.png.
        /// </summary>
        internal static string icon__SnipeIcon {
            get {
                return ResourceManager.GetString("icon__SnipeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Passive 1/Standard Ammo.png.
        /// </summary>
        internal static string icon__StandardAmmoIcon {
            get {
                return ResourceManager.GetString("icon__StandardAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M2/Steady Aim.png.
        /// </summary>
        internal static string icon__SteadyAimIcon {
            get {
                return ResourceManager.GetString("icon__SteadyAimIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        internal static string lang__LOADOUT_SNIPER_AMMO {
            get {
                return ResourceManager.GetString("lang__LOADOUT_SNIPER_AMMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string lang__LOADOUT_SNIPER_PASSIVE {
            get {
                return ResourceManager.GetString("lang__LOADOUT_SNIPER_PASSIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;style=cIsDamage&gt;0.45x&lt;/style&gt; damage. &lt;style=cIsDamage&gt;Explodes&lt;/style&gt; on hit for &lt;style=cIsDamage&gt;0.45x&lt;/style&gt; damage to nearby enemies. &lt;style=cIsUtility&gt;Boosts increase the size of the explosion&lt;/style&gt;..
        /// </summary>
        internal static string lang__SNIPER_AMMO_EXPLOSIVE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_EXPLOSIVE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive.
        /// </summary>
        internal static string lang__SNIPER_AMMO_EXPLOSIVE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_EXPLOSIVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 0% primary damage, applies a stacking burn that deals 215% primary damage over 10 seconds..
        /// </summary>
        internal static string lang__SNIPER_AMMO_PLASMA_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_PLASMA_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma.
        /// </summary>
        internal static string lang__SNIPER_AMMO_PLASMA_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_PLASMA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals up to 175% primary damage, fires a spread of pellets, damage falls off with range..
        /// </summary>
        internal static string lang__SNIPER_AMMO_SCATTER_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_SCATTER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        internal static string lang__SNIPER_AMMO_SCATTER_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_SCATTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains to enemies near your target.
        /// </summary>
        internal static string lang__SNIPER_AMMO_SHOCK_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_SHOCK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock.
        /// </summary>
        internal static string lang__SNIPER_AMMO_SHOCK_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_SHOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;style=cIsDamage&gt;1.0x&lt;/style&gt; damage, &lt;style=cIsUtility&gt;pierces enemies&lt;/style&gt;, and has a &lt;style=cIsUtility&gt;chance to ricochet&lt;/style&gt;..
        /// </summary>
        internal static string lang__SNIPER_AMMO_STANDARD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_STANDARD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Metal Jacket.
        /// </summary>
        internal static string lang__SNIPER_AMMO_STANDARD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_STANDARD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper is a long ranged, single-target dps that incorperates elements of an assassin to stay alive.\n
        ///
        ///They excel at taking down bosses and high priority targets but struggle against larger groups of weak enemies.\n.
        /// </summary>
        internal static string lang__SNIPER_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        internal static string lang__SNIPER_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style=cIsUtility&gt;Critical Strikes&lt;/style&gt; deal &lt;style=cIsDamage&gt;1.2x&lt;/style&gt; damage.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_CRITICAL_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_CRITICAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise Aim.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_CRITICAL_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_CRITICAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting enemies in the head deals 50% more damage (Unfinished for most enemies).
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_HEADSHOT_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_HEADSHOT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_HEADSHOT_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_HEADSHOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire for 280% damage. Reloading at the right time grants up to double damage..
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposition.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload and dash.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_RELOAD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_RELOAD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_RELOAD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_RELOAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot enemies for &lt;style=cIsDamage&gt;360% to 900%&lt;/style&gt; damage. Must be &lt;style=cIsUtility&gt;reloaded&lt;/style&gt; after each shot. Reloading at the right time &lt;style=cIsDamage&gt;increases damage&lt;/style&gt;..
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are you reading this??? Shouldn&apos;t you be playing the game?.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_RELOAD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_RELOAD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_RELOAD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_RELOAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style=cIsUtility&gt;Boost&lt;/style&gt; your shots by &lt;style=cIsDamage&gt;2.0x&lt;/style&gt;. &lt;style=cIsUtility&gt;Recharges quickly&lt;/style&gt; and can hold &lt;style=cIsUtility&gt;multiple stock&lt;/style&gt;..
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_QUICK_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_QUICK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickscope.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_QUICK_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_QUICK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style=cIsUtility&gt;Boost&lt;/style&gt; your shots by &lt;style=cIsDamage&gt;up to 6.5x&lt;/style&gt;. &lt;style=cIsUtility&gt;Charges faster&lt;/style&gt; while stationary. &lt;style=cIsHealth&gt;You are slowed while charging&lt;/style&gt;..
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_STEADY_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_STEADY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady Aim.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_STEADY_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_STEADY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT1_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceholderName3.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT2_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceholderName2.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT3_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceholderName1.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT4_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT4_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT5_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT5_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT6_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT6_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string lang__SNIPER_SKIN_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style=cIsUtility&gt;Stealth&lt;/style&gt; for 2 seconds and leave behind a &lt;style=cIsUtility&gt;Decoy&lt;/style&gt; that distracts enemies. You can &lt;style=cIsUtility&gt;Reactivate&lt;/style&gt; to detonate the decoy, dealing &lt;style=cIsDamage&gt;500%&lt;/style&gt; damage, &lt;style=cIsUtility&gt;stunning, and weakening&lt;/style&gt; nearby enemies..
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_DECOY_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_DECOY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_DECOY_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_DECOY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw a knife that deals 100% damage and sticks on hit. Reactivate to teleport to the knife, dealing 200% damage and marking nearby enemies. Killing a marked enemy resets all your cooldowns..
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_KNIFE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_KNIFE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink Knife.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_KNIFE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_KNIFE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Insert cool thing here].
        /// </summary>
        internal static string lang__SNIPER_SUBTITLE {
            get {
                return ResourceManager.GetString("lang__SNIPER_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a flip away from the direction you are aiming..
        /// </summary>
        internal static string lang__SNIPER_UTILITY_BACKFLIP_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_UTILITY_BACKFLIP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backflip.
        /// </summary>
        internal static string lang__SNIPER_UTILITY_BACKFLIP_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_UTILITY_BACKFLIP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/UI Prefabs/SniperCrosshair.prefab.
        /// </summary>
        internal static string prefab__Crosshair {
            get {
                return ResourceManager.GetString("prefab__Crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/KnifeProjectileGhost.prefab.
        /// </summary>
        internal static string prefab__KnifeGhostPrefab {
            get {
                return ResourceManager.GetString("prefab__KnifeGhostPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/mdlSniper.prefab.
        /// </summary>
        internal static string prefab__SniperPrefab {
            get {
                return ResourceManager.GetString("prefab__SniperPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rein_Sniper_Bank {
            get {
                object obj = ResourceManager.GetObject("Rein_Sniper_Bank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReinCore {
            get {
                object obj = ResourceManager.GetObject("ReinCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Stealth_MainTex.
        /// </summary>
        internal static string skin__Railgun_Diffuse {
            get {
                return ResourceManager.GetString("skin__Railgun_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string skin__Railgun_Emissive {
            get {
                return ResourceManager.GetString("skin__Railgun_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__Railgun_Normal {
            get {
                return ResourceManager.GetString("skin__Railgun_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Classic_MainTex.
        /// </summary>
        internal static string skin__RailgunAlt1_Diffuse {
            get {
                return ResourceManager.GetString("skin__RailgunAlt1_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string skin__RailgunAlt1_Emissive {
            get {
                return ResourceManager.GetString("skin__RailgunAlt1_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__RailgunAlt1_Normal {
            get {
                return ResourceManager.GetString("skin__RailgunAlt1_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_BlackGold_MainTex.
        /// </summary>
        internal static string skin__RailgunAlt2_Diffuse {
            get {
                return ResourceManager.GetString("skin__RailgunAlt2_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string skin__RailgunAlt2_Emissive {
            get {
                return ResourceManager.GetString("skin__RailgunAlt2_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__RailgunAlt2_Normal {
            get {
                return ResourceManager.GetString("skin__RailgunAlt2_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_MainTex.
        /// </summary>
        internal static string skin__RailgunAlt3_Diffuse {
            get {
                return ResourceManager.GetString("skin__RailgunAlt3_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string skin__RailgunAlt3_Emissive {
            get {
                return ResourceManager.GetString("skin__RailgunAlt3_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__RailgunAlt3_Normal {
            get {
                return ResourceManager.GetString("skin__RailgunAlt3_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_BlackGold_MainTex.
        /// </summary>
        internal static string skin__RailgunAlt4_Diffuse {
            get {
                return ResourceManager.GetString("skin__RailgunAlt4_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string skin__RailgunAlt4_Emissive {
            get {
                return ResourceManager.GetString("skin__RailgunAlt4_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__RailgunAlt4_Normal {
            get {
                return ResourceManager.GetString("skin__RailgunAlt4_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Jungle_MainTex.
        /// </summary>
        internal static string skin__RailgunAlt5_Diffuse {
            get {
                return ResourceManager.GetString("skin__RailgunAlt5_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string skin__RailgunAlt5_Emissive {
            get {
                return ResourceManager.GetString("skin__RailgunAlt5_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__RailgunAlt5_Normal {
            get {
                return ResourceManager.GetString("skin__RailgunAlt5_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Snow_MainTex.
        /// </summary>
        internal static string skin__RailgunAlt6_Diffuse {
            get {
                return ResourceManager.GetString("skin__RailgunAlt6_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Snow_Emission.
        /// </summary>
        internal static string skin__RailgunAlt6_Emissive {
            get {
                return ResourceManager.GetString("skin__RailgunAlt6_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string skin__RailgunAlt6_Normal {
            get {
                return ResourceManager.GetString("skin__RailgunAlt6_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_UrbanCamo_MainTex.
        /// </summary>
        internal static string skin__Sniper_Diffuse {
            get {
                return ResourceManager.GetString("skin__Sniper_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Uncolored_Emission.
        /// </summary>
        internal static string skin__Sniper_Emissive {
            get {
                return ResourceManager.GetString("skin__Sniper_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string skin__Sniper_Normal {
            get {
                return ResourceManager.GetString("skin__Sniper_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Classic_MainTex.
        /// </summary>
        internal static string skin__SniperAlt1_Diffuse {
            get {
                return ResourceManager.GetString("skin__SniperAlt1_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Classic_Emission.
        /// </summary>
        internal static string skin__SniperAlt1_Emissive {
            get {
                return ResourceManager.GetString("skin__SniperAlt1_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string skin__SniperAlt1_Normal {
            get {
                return ResourceManager.GetString("skin__SniperAlt1_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_MainTex.
        /// </summary>
        internal static string skin__SniperAlt2_Diffuse {
            get {
                return ResourceManager.GetString("skin__SniperAlt2_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Emission.
        /// </summary>
        internal static string skin__SniperAlt2_Emissive {
            get {
                return ResourceManager.GetString("skin__SniperAlt2_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string skin__SniperAlt2_Normal {
            get {
                return ResourceManager.GetString("skin__SniperAlt2_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_GreenCamo_MainTex.
        /// </summary>
        internal static string skin__SniperAlt3_Diffuse {
            get {
                return ResourceManager.GetString("skin__SniperAlt3_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Uncolored_Emission.
        /// </summary>
        internal static string skin__SniperAlt3_Emissive {
            get {
                return ResourceManager.GetString("skin__SniperAlt3_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string skin__SniperAlt3_Normal {
            get {
                return ResourceManager.GetString("skin__SniperAlt3_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_MainTex.
        /// </summary>
        internal static string skin__SniperAlt4_Diffuse {
            get {
                return ResourceManager.GetString("skin__SniperAlt4_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_Emission.
        /// </summary>
        internal static string skin__SniperAlt4_Emissive {
            get {
                return ResourceManager.GetString("skin__SniperAlt4_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string skin__SniperAlt4_Normal {
            get {
                return ResourceManager.GetString("skin__SniperAlt4_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Jungle_MainTex.
        /// </summary>
        internal static string skin__SniperAlt5_Diffuse {
            get {
                return ResourceManager.GetString("skin__SniperAlt5_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Uncolored_Emission.
        /// </summary>
        internal static string skin__SniperAlt5_Emissive {
            get {
                return ResourceManager.GetString("skin__SniperAlt5_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string skin__SniperAlt5_Normal {
            get {
                return ResourceManager.GetString("skin__SniperAlt5_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Snow_MainTex.
        /// </summary>
        internal static string skin__SniperAlt6_Diffuse {
            get {
                return ResourceManager.GetString("skin__SniperAlt6_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Snow_Emission.
        /// </summary>
        internal static string skin__SniperAlt6_Emissive {
            get {
                return ResourceManager.GetString("skin__SniperAlt6_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Snow_Normal.
        /// </summary>
        internal static string skin__SniperAlt6_Normal {
            get {
                return ResourceManager.GetString("skin__SniperAlt6_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnife_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnife_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnife_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnife_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnife_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnife_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnifeAlt1_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt1_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnifeAlt1_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt1_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnifeAlt1_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt1_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnifeAlt2_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt2_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnifeAlt2_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt2_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnifeAlt2_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt2_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnifeAlt3_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt3_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnifeAlt3_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt3_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnifeAlt3_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt3_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnifeAlt4_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt4_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnifeAlt4_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt4_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnifeAlt4_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt4_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnifeAlt5_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt5_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnifeAlt5_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt5_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnifeAlt5_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt5_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_MainTex.
        /// </summary>
        internal static string skin__ThrowKnifeAlt6_Diffuse {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt6_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_Emission.
        /// </summary>
        internal static string skin__ThrowKnifeAlt6_Emissive {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt6_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string skin__ThrowKnifeAlt6_Normal {
            get {
                return ResourceManager.GetString("skin__ThrowKnifeAlt6_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sniper {
            get {
                object obj = ResourceManager.GetObject("sniper", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
