//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Utility/Backflip.png.
        /// </summary>
        internal static string BackflipIcon {
            get {
                return ResourceManager.GetString("BackflipIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/passive 2/Precise Aim.png.
        /// </summary>
        internal static string CritPassiveIcon {
            get {
                return ResourceManager.GetString("CritPassiveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DecoyIcon {
            get {
                return ResourceManager.GetString("DecoyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DecoyReactivateIcon {
            get {
                return ResourceManager.GetString("DecoyReactivateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Passive 1/Explosive Ammo.png.
        /// </summary>
        internal static string ExplosiveAmmoIcon {
            get {
                return ResourceManager.GetString("ExplosiveAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/passive 2/Headshot.png.
        /// </summary>
        internal static string HeadshotIcon {
            get {
                return ResourceManager.GetString("HeadshotIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KnifeIcon {
            get {
                return ResourceManager.GetString("KnifeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KnifeReactivateIcon {
            get {
                return ResourceManager.GetString("KnifeReactivateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        internal static string lang__LOADOUT_SNIPER_AMMO {
            get {
                return ResourceManager.GetString("lang__LOADOUT_SNIPER_AMMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string lang__LOADOUT_SNIPER_PASSIVE {
            get {
                return ResourceManager.GetString("lang__LOADOUT_SNIPER_PASSIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explodes on hit for damage to all nearby enemies..
        /// </summary>
        internal static string lang__SNIPER_AMMO_EXPLOSIVE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_EXPLOSIVE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive Ammo.
        /// </summary>
        internal static string lang__SNIPER_AMMO_EXPLOSIVE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_EXPLOSIVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo that can pierce and ricochet.
        /// </summary>
        internal static string lang__SNIPER_AMMO_STANDARD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_STANDARD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Metal Jacket.
        /// </summary>
        internal static string lang__SNIPER_AMMO_STANDARD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_STANDARD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO  \n.
        /// </summary>
        internal static string lang__SNIPER_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        internal static string lang__SNIPER_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Strikes deal 20% more damage.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_CRITICAL_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_CRITICAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise Aim.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_CRITICAL_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_CRITICAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting enemies in the head deals 50% more damage.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_HEADSHOT_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_HEADSHOT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_HEADSHOT_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_HEADSHOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire, and dash when reloading.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposition.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload and dash.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_RELOAD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_RELOAD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_RELOAD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_RELOAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot enemies.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_RELOAD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_RELOAD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_RELOAD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_RELOAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire off a quick to aim, powerful shot while maintaining mobility.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_QUICK_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_QUICK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickscope.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_QUICK_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_QUICK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge up a powerful shot for up to 1000% primary damage.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_STEADY_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_STEADY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady Aim.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_STEADY_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_STEADY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT1_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT2_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed2.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT3_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed3.
        /// </summary>
        internal static string lang__SNIPER_SKIN_ALT4_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_ALT4_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string lang__SNIPER_SKIN_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SKIN_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a decoy.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_DECOY_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_DECOY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_DECOY_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_DECOY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dennis.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_KNIFE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_KNIFE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENNIS.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_KNIFE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_KNIFE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Insert cool thing here].
        /// </summary>
        internal static string lang__SNIPER_SUBTITLE {
            get {
                return ResourceManager.GetString("lang__SNIPER_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do a backflip.
        /// </summary>
        internal static string lang__SNIPER_UTILITY_BACKFLIP_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_UTILITY_BACKFLIP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Training.
        /// </summary>
        internal static string lang__SNIPER_UTILITY_BACKFLIP_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_UTILITY_BACKFLIP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Other/portraitIcon.png.
        /// </summary>
        internal static string PortraitIcon {
            get {
                return ResourceManager.GetString("PortraitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickscopeIcon {
            get {
                return ResourceManager.GetString("QuickscopeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Classic_MainTex.
        /// </summary>
        internal static string RailgunAlt1_Diffuse {
            get {
                return ResourceManager.GetString("RailgunAlt1_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_White_Emission.
        /// </summary>
        internal static string RailgunAlt1_Emissive {
            get {
                return ResourceManager.GetString("RailgunAlt1_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string RailgunAlt1_Normal {
            get {
                return ResourceManager.GetString("RailgunAlt1_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_BlackGold_MainTex.
        /// </summary>
        internal static string RailgunAlt2_Diffuse {
            get {
                return ResourceManager.GetString("RailgunAlt2_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_BlackGold_Emission.
        /// </summary>
        internal static string RailgunAlt2_Emissive {
            get {
                return ResourceManager.GetString("RailgunAlt2_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string RailgunAlt2_Normal {
            get {
                return ResourceManager.GetString("RailgunAlt2_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_MainTex.
        /// </summary>
        internal static string RailgunAlt3_Diffuse {
            get {
                return ResourceManager.GetString("RailgunAlt3_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Emission.
        /// </summary>
        internal static string RailgunAlt3_Emissive {
            get {
                return ResourceManager.GetString("RailgunAlt3_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string RailgunAlt3_Normal {
            get {
                return ResourceManager.GetString("RailgunAlt3_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Stealth_MainTex.
        /// </summary>
        internal static string RailgunDefault_Diffuse {
            get {
                return ResourceManager.GetString("RailgunDefault_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_Stealth_Emission.
        /// </summary>
        internal static string RailgunDefault_Emissive {
            get {
                return ResourceManager.GetString("RailgunDefault_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun_GreenGoldUrban_Normal.
        /// </summary>
        internal static string RailgunDefault_Normal {
            get {
                return ResourceManager.GetString("RailgunDefault_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rein_Sniper_Bank {
            get {
                object obj = ResourceManager.GetObject("Rein_Sniper_Bank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReinCore {
            get {
                object obj = ResourceManager.GetObject("ReinCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M1/Reload.png.
        /// </summary>
        internal static string ReloadIcon {
            get {
                return ResourceManager.GetString("ReloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlideIcon {
            get {
                return ResourceManager.GetString("SlideIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M1/Reload.png.
        /// </summary>
        internal static string SlideReloadIcon {
            get {
                return ResourceManager.GetString("SlideReloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M1/Snipe.png.
        /// </summary>
        internal static string SnipeIcon {
            get {
                return ResourceManager.GetString("SnipeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sniper {
            get {
                object obj = ResourceManager.GetObject("sniper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_UrbanCamo_MainTex.
        /// </summary>
        internal static string SniperDefault_Diffuse {
            get {
                return ResourceManager.GetString("SniperDefault_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_UrbanCamo_Emission.
        /// </summary>
        internal static string SniperDefault_Emissive {
            get {
                return ResourceManager.GetString("SniperDefault_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_GreenCamo_Normal.
        /// </summary>
        internal static string SniperDefault_Normal {
            get {
                return ResourceManager.GetString("SniperDefault_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/mdlSniper.prefab.
        /// </summary>
        internal static string SniperPrefabPath {
            get {
                return ResourceManager.GetString("SniperPrefabPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Classic_MainTex.
        /// </summary>
        internal static string SniperSkin1_Diffuse {
            get {
                return ResourceManager.GetString("SniperSkin1_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Classic_Emission.
        /// </summary>
        internal static string SniperSkin1_Emissive {
            get {
                return ResourceManager.GetString("SniperSkin1_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_GreenCamo_Normal.
        /// </summary>
        internal static string SniperSkin1_Normal {
            get {
                return ResourceManager.GetString("SniperSkin1_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_MainTex.
        /// </summary>
        internal static string SniperSkin2_Diffuse {
            get {
                return ResourceManager.GetString("SniperSkin2_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Emission.
        /// </summary>
        internal static string SniperSkin2_Emissive {
            get {
                return ResourceManager.GetString("SniperSkin2_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string SniperSkin2_Normal {
            get {
                return ResourceManager.GetString("SniperSkin2_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_GreenCamo_MainTex.
        /// </summary>
        internal static string SniperSkin3_Diffuse {
            get {
                return ResourceManager.GetString("SniperSkin3_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_GreenCamo_Emission.
        /// </summary>
        internal static string SniperSkin3_Emissive {
            get {
                return ResourceManager.GetString("SniperSkin3_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_GreenCamo_Normal.
        /// </summary>
        internal static string SniperSkin3_Normal {
            get {
                return ResourceManager.GetString("SniperSkin3_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_MainTex.
        /// </summary>
        internal static string SniperSkin4_Diffuse {
            get {
                return ResourceManager.GetString("SniperSkin4_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_Emission.
        /// </summary>
        internal static string SniperSkin4_Emissive {
            get {
                return ResourceManager.GetString("SniperSkin4_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_RedBlack_Normal.
        /// </summary>
        internal static string SniperSkin4_Normal {
            get {
                return ResourceManager.GetString("SniperSkin4_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_MainTex.
        /// </summary>
        internal static string SniperSkin5_Diffuse {
            get {
                return ResourceManager.GetString("SniperSkin5_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_Emission.
        /// </summary>
        internal static string SniperSkin5_Emissive {
            get {
                return ResourceManager.GetString("SniperSkin5_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper_Red_Normal.
        /// </summary>
        internal static string SniperSkin5_Normal {
            get {
                return ResourceManager.GetString("SniperSkin5_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/Passive 1/Standard Ammo.png.
        /// </summary>
        internal static string StandardAmmoIcon {
            get {
                return ResourceManager.GetString("StandardAmmoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/__EXPORT/Icons/M2/Steady Aim.png.
        /// </summary>
        internal static string SteadyAimIcon {
            get {
                return ResourceManager.GetString("SteadyAimIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_MainTex.
        /// </summary>
        internal static string ThrowKnifeDefault_Diffuse {
            get {
                return ResourceManager.GetString("ThrowKnifeDefault_Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Emission.
        /// </summary>
        internal static string ThrowKnifeDefault_Emissive {
            get {
                return ResourceManager.GetString("ThrowKnifeDefault_Emissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThrowKnife_GreenBlack_Normal.
        /// </summary>
        internal static string ThrowKnifeDefault_Normal {
            get {
                return ResourceManager.GetString("ThrowKnifeDefault_Normal", resourceCulture);
            }
        }
    }
}
