//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gauss_Diffuse {
            get {
                object obj = ResourceManager.GetObject("Gauss_Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gauss_Emissive {
            get {
                object obj = ResourceManager.GetObject("Gauss_Emissive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gauss_Metal {
            get {
                object obj = ResourceManager.GetObject("Gauss_Metal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gauss_Normals {
            get {
                object obj = ResourceManager.GetObject("Gauss_Normals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        internal static string lang__LOADOUT_SNIPER_AMMO {
            get {
                return ResourceManager.GetString("lang__LOADOUT_SNIPER_AMMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string lang__LOADOUT_SNIPER_PASSIVE {
            get {
                return ResourceManager.GetString("lang__LOADOUT_SNIPER_PASSIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierces stuff!.
        /// </summary>
        internal static string lang__SNIPER_AMMO_PIERCING_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_PIERCING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercing Ammo.
        /// </summary>
        internal static string lang__SNIPER_AMMO_PIERCING_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_PIERCING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does standard stuff!.
        /// </summary>
        internal static string lang__SNIPER_AMMO_STANDARD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_STANDARD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Ammo.
        /// </summary>
        internal static string lang__SNIPER_AMMO_STANDARD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_AMMO_STANDARD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe later \n.
        /// </summary>
        internal static string lang__SNIPER_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        internal static string lang__SNIPER_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Strikes deal 20% more damage.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_CRITICAL_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_CRITICAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise Aim.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_CRITICAL_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_CRITICAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting enemies in the head deals 50% more damage.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_HEADSHOT_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_HEADSHOT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot.
        /// </summary>
        internal static string lang__SNIPER_PASSIVE_HEADSHOT_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PASSIVE_HEADSHOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip stuff and dash.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposition.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload your primary and do a cool slide.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_RELOAD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_RELOAD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_DASH_RELOAD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_DASH_RELOAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe stuff.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload your primary.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_RELOAD_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_RELOAD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string lang__SNIPER_PRIMARY_SNIPE_RELOAD_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_PRIMARY_SNIPE_RELOAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t aim at all.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_QUICK_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_QUICK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickscope.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_QUICK_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_QUICK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim steadily.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_STEADY_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_STEADY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady Aim.
        /// </summary>
        internal static string lang__SNIPER_SECONDARY_STEADY_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SECONDARY_STEADY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a decoy.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_DECOY_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_DECOY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_DECOY_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_DECOY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink to a knife.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_KNIFE_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_KNIFE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink Knife.
        /// </summary>
        internal static string lang__SNIPER_SPECIAL_KNIFE_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_SPECIAL_KNIFE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Insert cool thing here].
        /// </summary>
        internal static string lang__SNIPER_SUBTITLE {
            get {
                return ResourceManager.GetString("lang__SNIPER_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do a backflip.
        /// </summary>
        internal static string lang__SNIPER_UTILITY_BACKFLIP_DESC {
            get {
                return ResourceManager.GetString("lang__SNIPER_UTILITY_BACKFLIP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Training.
        /// </summary>
        internal static string lang__SNIPER_UTILITY_BACKFLIP_NAME {
            get {
                return ResourceManager.GetString("lang__SNIPER_UTILITY_BACKFLIP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReinCore {
            get {
                object obj = ResourceManager.GetObject("ReinCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sniper {
            get {
                object obj = ResourceManager.GetObject("sniper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sniper_Emissive_2__1_ {
            get {
                object obj = ResourceManager.GetObject("Sniper_Emissive_2__1_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperDiffuse {
            get {
                object obj = ResourceManager.GetObject("SniperDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperNormal {
            get {
                object obj = ResourceManager.GetObject("SniperNormal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/Prefabs/mdlSniper.prefab.
        /// </summary>
        internal static string SniperPrefabPath {
            get {
                return ResourceManager.GetString("SniperPrefabPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] unknown__11_ {
            get {
                object obj = ResourceManager.GetObject("unknown__11_", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
