using System;
using System.Collections.Generic;
using System.Text;

namespace ReinCore
{
    public enum GlobalKeys
    {
        AllKeys = -1,
        None = 0,
        //Row 0
        Esc,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PrintScreen,
        PauseBreak,
        Mode_ScrollLock,
        A1,
        A2,
        A3,
        Mode,
        //Row 1
        Tilda,
        N1,
        N2,
        N3,
        N4,
        N5,
        N6,
        N7,
        N8,
        N9,
        N0,
        Minus,
        Equals,
        Backspace,
        Insert,
        Home,
        PageUp,
        NumLock,
        NumSlash,
        NumMulti,
        NumMinus,
        //Row 2
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        OpenBracket,
        CloseBracket,
        ANSI_Backslash,
        Delete,
        End,
        PageDown,
        Num7,
        Num8,
        Num9,
        NumPlus,
        //Row 3
        CapsLock,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        SemiColon,
        Apostophe,
        ISO_Hash,
        Enter,
        Num4,
        Num5,
        Num6,
        //Row 4
        LeftShift,
        ISO_Blackslash,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        Period,
        Slash,
        RightShift,
        Up,
        Num1,
        Num2,
        Num3,
        NumEnter,
        //Row 5
        LeftCtrl,
        LeftWin,
        LeftAlt,
        Space,
        RightAlt,
        RightWin,
        Function,
        RightControl,
        Left,
        Down,
        Right,
        Num0,
        NumPeriod
    }
}
